<a href="https://colab.research.google.com/github/muneeswarikagitala-web/meenu/blob/main/pandas_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
arr =np.array([10,20,30,40,50])
marks=pd.Series(arr)
print(marks)
print(marks[0])

0    10
1    20
2    30
3    40
4    50
dtype: int64
10

In [ ]:
marks=pd.Series(
    [10,20,30],
    index=["math","phy","chem"]
)
print(marks)

math    10
phy     20
chem    30
dtype: int64

In [ ]:
marks=pd.Series(
    [10,20,30],
    index=["math","phy","chem"]
)
print(marks)
print(marks["math"])
print(marks.shape)
print(marks.size)
print(marks.dtype)
print(marks.values)
print(marks.index)

math    10
phy     20
chem    30
dtype: int64
10
(3,)
3
int64
[10 20 30]
Index(['math', 'phy', 'chem'], dtype='object')

In [ ]:
numbers=[1,2,34,7]
result=[]
for i in numbers:
  result.append(i*2)
print(result)

[2, 4, 68, 14]

In [ ]:
#vectorized operation means applying one
#operation to all elements automatically
#without writing loops

numbers=[1,2,34,7]
arr=np.array(numbers)
print(arr*2)

[ 2  4 68 14]

In [ ]:
data=pd.Series([10,20,30,40,np.nan,50])
print(data.isnull())#to know any null values
print(data.fillna(0))#to fill null values

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool
0    10.0
1    20.0
2    30.0
3    40.0
4     0.0
5    50.0
dtype: float64

In [ ]:
#dataframe
data={
    "name:":["muni","meenu","jennie","rosie"],
    "marks:":[60,99,100,98],
    "city:":["tpt","skht","paris","australia"]
}
df=pd.DataFrame(data)
print(df)
print(df.shape)
print(df.size)
print(df.columns)
print(df.dtypes)
print(df.index)

    name:  marks:      city:
0    muni      60        tpt
1   meenu      99       skht
2  jennie     100      paris
3   rosie      98  australia
(4, 3)
12
Index(['name:', 'marks:', 'city:'], dtype='object')
name:     object
marks:     int64
city:     object
dtype: object
RangeIndex(start=0, stop=4, step=1)

In [ ]:
#adding data by adding grade
df["Grade"]=["B","B","B","C"]
print(df) # adding grade data

    name:  marks:      city: Grade
0    muni      60        tpt     B
1   meenu      99       skht     B
2  jennie     100      paris     B
3   rosie      98  australia     C

In [ ]:
df["marks:"]=df["marks:"]+20
print(df) # adding marks

    name:  marks:      city: Grade
0    muni      80        tpt     B
1   meenu     119       skht     B
2  jennie     120      paris     B
3   rosie     118  australia     C

In [ ]:
df["marks:"]=df["marks:"]+20
print(df) # removing
df=df.drop("city:",axis=1)#axis 1 is coloumn and # axis0 is row
print(df)

    name:  marks:      city: Grade
0    muni     140        tpt     B
1   meenu     179       skht     B
2  jennie     180      paris     B
3   rosie     178  australia     C
    name:  marks: Grade
0    muni     140     B
1   meenu     179     B
2  jennie     180     B
3   rosie     178     C

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/datsetsfordatasciencebytexl/student_dataset_20rows.csv")
print(df)

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [ ]:
df=pd.read_json("/content/drive/MyDrive/datsetsfordatasciencebytexl/student_dataset_20rows.json")
print(df)

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [ ]:
import pandas as pd
df=pd.read_excel("/content/drive/MyDrive/datsetsfordatasciencebytexl/student_dataset_20rows.xlsx")
print(df)

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [ ]:
df.iloc[[0,1,2,3]]

   Student_ID   Name  Age        Course  Marks        City
0         101    Ram   25        Pandas     90  Vijayawada
1         102   Ravi   23         NumPy     81   Hyderabad
2         103   Sita   21        Python     80     Chennai
3         104  Kiran   21  Data Science     98   Bangalore

In [ ]:
df.loc[0:2]

   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai

In [ ]:
df.loc[:,"Name"]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [ ]:
df.loc[:,["Name","Marks"]]

       Name  Marks
0       Ram     90
1      Ravi     81
2      Sita     80
3     Kiran     98
4       Anu     70
5     Rahul     82
6     Sneha     79
7     Arjun     70
8     Pooja     95
9    Vikram     72
10    Divya     94
11     Ajay     84
12  Keerthi     74
13   Nikhil     99
14    Meena     81
15      Sai     97
16  Lavanya     72
17    Rohit     70
18     Teja     90
19    Priya     78

In [ ]:
df.loc[5:8,["Name","Age","City"]]

    Name  Age     City
5  Rahul   22    Delhi
6  Sneha   25     Pune
7  Arjun   22  Kolkata
8  Pooja   20    Vizag

In [ ]:
#suppose if i am accesing multiple rows
#in iloc function suppose my range is 0 to n>i will get output as 0 to n-1
#in loc funtion suppose my range is 0 to

In [ ]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'City'], dtype='object')

In [ ]:
#task1:select name column (loc,iloc,normal)
print(df["Name"])
print(df.loc[:,"Name"])
print(df.iloc[:,1])
#task2:select name,city columns(loc,iloc,normal)
print(df[["Name","City"]])
print(df.loc[:,["Name","City"]])
print(df.iloc[:,[1,3]])
#task3:select first 3 rows(loc,iloc)
print(df.iloc[0:3])
print(df.loc[0:2])
#task4:select first 2 rows and first 2 columns (loc,iloc)
print(df.iloc[0:2,0:2])
print(df.loc[0:1,"student_ID","Name"])
#task5:select all rows and marks columns(loc,iloc)
print(df.loc[:,"Marks"])
print(df.iloc[:,4])

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object
0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object
0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object
       Name         City
0       Ram   Vijayawada
1      Ravi    Hyderabad
2      Sita      Chennai
3     Kiran    Bangalore
4       Anu       Mumbai
5     Rahul        Delhi
6     Sneha         Pune
7     Arjun      Kolkata
8     Pooja        Vizag
9    Vikram     Tirupati
10    Divya     Warangal
11     Ajay       Guntur
12  Keerthi      Nellore
13   Nikhil       Kadapa
14    Meena      Kurnool
15      Sai       Ongole
16  Lavanya  Rajahmundry
17    Rohit        Eluru
18     Teja      Khammam
19    Priya    Nizamabad
       Name         City
0       Ram   Vijayawada
1      Ravi    Hyderabad
2      Sita      Chennai
3     Kiran    Bangalore
4       Anu       Mumbai
5     Rahul        Delhi
6     Sneha         Pune
7     Arjun      Kolkata
8     Pooja        Vizag
9    Vikram     Tirupati
10    Divya     Warangal
11     Ajay       Guntur
12  Keerthi      Nellore
13   Nikhil       Kadapa
14    Meena      Kurnool
15      Sai       Ongole
16  Lavanya  Rajahmundry
17    Rohit        Eluru
18     Teja      Khammam
19    Priya    Nizamabad
       Name            Course
0       Ram            Pandas
1      Ravi             NumPy
2      Sita            Python
3     Kiran      Data Science
4       Anu            Pandas
5     Rahul               SQL
6     Sneha     Deep Learning
7     Arjun  Machine Learning
8     Pooja            Python
9    Vikram               SQL
10    Divya     Deep Learning
11     Ajay            Python
12  Keerthi             NumPy
13   Nikhil     Deep Learning
14    Meena                AI
15      Sai            Pandas
16  Lavanya                AI
17    Rohit            Python
18     Teja  Machine Learning
19    Priya               SQL
   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai
   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai
   Student_ID  Name
0         101   Ram
1         102  Ravi

IndexingError: Too many indexers

In [ ]:
print(df.iloc[:,1])
print(df.loc[:,"Name"])
print(df["Name"])

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object
0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object
0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [ ]:
df.loc[:,["Name","City"]]

       Name         City
0       Ram   Vijayawada
1      Ravi    Hyderabad
2      Sita      Chennai
3     Kiran    Bangalore
4       Anu       Mumbai
5     Rahul        Delhi
6     Sneha         Pune
7     Arjun      Kolkata
8     Pooja        Vizag
9    Vikram     Tirupati
10    Divya     Warangal
11     Ajay       Guntur
12  Keerthi      Nellore
13   Nikhil       Kadapa
14    Meena      Kurnool
15      Sai       Ongole
16  Lavanya  Rajahmundry
17    Rohit        Eluru
18     Teja      Khammam
19    Priya    Nizamabad

In [ ]:
df[df["Marks"]>80]#filteringgggggg

    Student_ID    Name  Age            Course  Marks        City
0          101     Ram   25            Pandas     90  Vijayawada
1          102    Ravi   23             NumPy     81   Hyderabad
3          104   Kiran   21      Data Science     98   Bangalore
5          106   Rahul   22               SQL     82       Delhi
8          109   Pooja   20            Python     95       Vizag
10         111   Divya   23     Deep Learning     94    Warangal
11         112    Ajay   21            Python     84      Guntur
13         114  Nikhil   22     Deep Learning     99      Kadapa
14         115   Meena   23                AI     81     Kurnool
15         116     Sai   25            Pandas     97      Ongole
18         119    Teja   25  Machine Learning     90     Khammam

In [ ]:
df[df["Marks"]<=90]

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
9          110   Vikram   20               SQL     72     Tirupati
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
14         115    Meena   23                AI     81      Kurnool
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [ ]:
df[df["Marks"]>25]

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [ ]:
df[df["Age"]==20]

    Student_ID     Name  Age  Course  Marks         City
4          105      Anu   20  Pandas     70       Mumbai
8          109    Pooja   20  Python     95        Vizag
9          110   Vikram   20     SQL     72     Tirupati
16         117  Lavanya   20      AI     72  Rajahmundry

In [ ]:
#combinatin of filtering
df[(df["Marks"]>80) & (df["Age"]>=21)] #and operation two true

    Student_ID    Name  Age            Course  Marks        City
0          101     Ram   25            Pandas     90  Vijayawada
1          102    Ravi   23             NumPy     81   Hyderabad
3          104   Kiran   21      Data Science     98   Bangalore
5          106   Rahul   22               SQL     82       Delhi
10         111   Divya   23     Deep Learning     94    Warangal
11         112    Ajay   21            Python     84      Guntur
13         114  Nikhil   22     Deep Learning     99      Kadapa
14         115   Meena   23                AI     81     Kurnool
15         116     Sai   25            Pandas     97      Ongole
18         119    Teja   25  Machine Learning     90     Khammam

In [ ]:
df[(df["Marks"]>80) | (df["Age"]>=21)] #or operation anything true on both any 1 true

    Student_ID     Name  Age            Course  Marks        City
0          101      Ram   25            Pandas     90  Vijayawada
1          102     Ravi   23             NumPy     81   Hyderabad
2          103     Sita   21            Python     80     Chennai
3          104    Kiran   21      Data Science     98   Bangalore
5          106    Rahul   22               SQL     82       Delhi
6          107    Sneha   25     Deep Learning     79        Pune
7          108    Arjun   22  Machine Learning     70     Kolkata
8          109    Pooja   20            Python     95       Vizag
10         111    Divya   23     Deep Learning     94    Warangal
11         112     Ajay   21            Python     84      Guntur
12         113  Keerthi   21             NumPy     74     Nellore
13         114   Nikhil   22     Deep Learning     99      Kadapa
14         115    Meena   23                AI     81     Kurnool
15         116      Sai   25            Pandas     97      Ongole
17         118    Rohit   23            Python     70       Eluru
18         119     Teja   25  Machine Learning     90     Khammam
19         120    Priya   22               SQL     78   Nizamabad

In [ ]:
print(df[(df["Marks"]>80) & (df["Course"]=="Pandas")])

    Student_ID Name  Age  Course  Marks        City
0          101  Ram   25  Pandas     90  Vijayawada
15         116  Sai   25  Pandas     97      Ongole

In [ ]:
print(df.loc[df["Marks"]>80,["Name","Marks"]])

      Name  Marks
0      Ram     90
1     Ravi     81
3    Kiran     98
5    Rahul     82
8    Pooja     95
10   Divya     94
11    Ajay     84
13  Nikhil     99
14   Meena     81
15     Sai     97
18    Teja     90

In [ ]:
#task1 filter studentsmarks with less than 70
print(df[df["Marks"]>70])
#task2 filter students from Bangalore
print(df[df["City"]=="Banglore"])
#task3 students age less than 30
print(df[df["Age"]<30])
#task4 students with marks greater than 25 0r age greater than 30
print(df[(df["Marks"]>25)|(df["Age"]>30)])
#task5 show only name and age where city is chennai
print(df.loc[df["City"]=="Chennai",["Name","Age"]])

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad
Empty DataFrame
Columns: [Student_ID, Name, Age, Course, Marks, City]
Index: []
    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad
    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad
   Name  Age
2  Sita   21

In [ ]:
df.iloc[0:2,0:4]

   Student_ID  Name  Age  Course
0         101   Ram   25  Pandas
1         102  Ravi   23   NumPy

In [ ]:
print(df[df["City"]=="Chennai"])

   Student_ID  Name  Age  Course  Marks     City
2         103  Sita   21  Python     80  Chennai

In [ ]:
print(df)

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [ ]:
#sorting asc and decsending order
#asc to desc
#df.sort_values(by=="column name")

In [ ]:
df.sort_values(by="Marks")#asc

    Student_ID     Name  Age            Course  Marks         City
7          108    Arjun   22  Machine Learning     70      Kolkata
4          105      Anu   20            Pandas     70       Mumbai
17         118    Rohit   23            Python     70        Eluru
9          110   Vikram   20               SQL     72     Tirupati
16         117  Lavanya   20                AI     72  Rajahmundry
12         113  Keerthi   21             NumPy     74      Nellore
19         120    Priya   22               SQL     78    Nizamabad
6          107    Sneha   25     Deep Learning     79         Pune
2          103     Sita   21            Python     80      Chennai
1          102     Ravi   23             NumPy     81    Hyderabad
14         115    Meena   23                AI     81      Kurnool
5          106    Rahul   22               SQL     82        Delhi
11         112     Ajay   21            Python     84       Guntur
18         119     Teja   25  Machine Learning     90      Khammam
0          101      Ram   25            Pandas     90   Vijayawada
10         111    Divya   23     Deep Learning     94     Warangal
8          109    Pooja   20            Python     95        Vizag
15         116      Sai   25            Pandas     97       Ongole
3          104    Kiran   21      Data Science     98    Bangalore
13         114   Nikhil   22     Deep Learning     99       Kadapa

In [ ]:
df.sort_values(by="Marks",ascending=False)#desc

    Student_ID     Name  Age            Course  Marks         City
13         114   Nikhil   22     Deep Learning     99       Kadapa
3          104    Kiran   21      Data Science     98    Bangalore
15         116      Sai   25            Pandas     97       Ongole
8          109    Pooja   20            Python     95        Vizag
10         111    Divya   23     Deep Learning     94     Warangal
18         119     Teja   25  Machine Learning     90      Khammam
0          101      Ram   25            Pandas     90   Vijayawada
11         112     Ajay   21            Python     84       Guntur
5          106    Rahul   22               SQL     82        Delhi
1          102     Ravi   23             NumPy     81    Hyderabad
14         115    Meena   23                AI     81      Kurnool
2          103     Sita   21            Python     80      Chennai
6          107    Sneha   25     Deep Learning     79         Pune
19         120    Priya   22               SQL     78    Nizamabad
12         113  Keerthi   21             NumPy     74      Nellore
9          110   Vikram   20               SQL     72     Tirupati
16         117  Lavanya   20                AI     72  Rajahmundry
7          108    Arjun   22  Machine Learning     70      Kolkata
4          105      Anu   20            Pandas     70       Mumbai
17         118    Rohit   23            Python     70        Eluru

In [ ]:
df.sort_values(by="City")

    Student_ID     Name  Age            Course  Marks         City
3          104    Kiran   21      Data Science     98    Bangalore
2          103     Sita   21            Python     80      Chennai
5          106    Rahul   22               SQL     82        Delhi
17         118    Rohit   23            Python     70        Eluru
11         112     Ajay   21            Python     84       Guntur
1          102     Ravi   23             NumPy     81    Hyderabad
13         114   Nikhil   22     Deep Learning     99       Kadapa
18         119     Teja   25  Machine Learning     90      Khammam
7          108    Arjun   22  Machine Learning     70      Kolkata
14         115    Meena   23                AI     81      Kurnool
4          105      Anu   20            Pandas     70       Mumbai
12         113  Keerthi   21             NumPy     74      Nellore
19         120    Priya   22               SQL     78    Nizamabad
15         116      Sai   25            Pandas     97       Ongole
6          107    Sneha   25     Deep Learning     79         Pune
16         117  Lavanya   20                AI     72  Rajahmundry
9          110   Vikram   20               SQL     72     Tirupati
0          101      Ram   25            Pandas     90   Vijayawada
8          109    Pooja   20            Python     95        Vizag
10         111    Divya   23     Deep Learning     94     Warangal

In [79]:
df.sort_values(by=["City","Marks"])

    Student_ID     Name  Age            Course  Marks         City
3          104    Kiran   21      Data Science     98    Bangalore
2          103     Sita   21            Python     80      Chennai
5          106    Rahul   22               SQL     82        Delhi
17         118    Rohit   23            Python     70        Eluru
11         112     Ajay   21            Python     84       Guntur
1          102     Ravi   23             NumPy     81    Hyderabad
13         114   Nikhil   22     Deep Learning     99       Kadapa
18         119     Teja   25  Machine Learning     90      Khammam
7          108    Arjun   22  Machine Learning     70      Kolkata
14         115    Meena   23                AI     81      Kurnool
4          105      Anu   20            Pandas     70       Mumbai
12         113  Keerthi   21             NumPy     74      Nellore
19         120    Priya   22               SQL     78    Nizamabad
15         116      Sai   25            Pandas     97       Ongole
6          107    Sneha   25     Deep Learning     79         Pune
16         117  Lavanya   20                AI     72  Rajahmundry
9          110   Vikram   20               SQL     72     Tirupati
0          101      Ram   25            Pandas     90   Vijayawada
8          109    Pooja   20            Python     95        Vizag
10         111    Divya   23     Deep Learning     94     Warangal